export const HOTEL_GRID_PAGE_SIZE_OPTIONS = [6, 9, 12, 18] as const
export const HOTEL_CARD_SKELETON_HEIGHT = 100
export const HOTEL_FILTER_MD_WIDTH = 220
export const PAYMENT_DIRECTION_FILTER_MD_WIDTH = 180
export const PAYMENT_TYPE_FILTER_MD_WIDTH = 200
