import { Document, Image, Page, Text, View } from '@react-pdf/renderer'
import type { DamageInvoice } from '../types/damageInvoice'
import { createDamageInvoiceTheme } from './theme'
import { createDamageInvoiceStyles } from '../styles/damageInvoiceStyle'
import { formatCurrency, formatDate } from '../utils/format'

interface DamageInvoiceDocumentProps {
  invoice: DamageInvoice
}

export function DamageInvoiceDocument({ invoice }: DamageInvoiceDocumentProps) {
  const theme = createDamageInvoiceTheme({
    primaryColor: invoice.hotelPrimaryColor,
    secondaryColor: invoice.hotelSecondaryColor,
  })
  const styles = createDamageInvoiceStyles(theme)

  const hotelInitials = invoice.hotelName
    .split(' ')
    .map(p => p[0])
    .join('')
    .slice(0, 2)
    .toUpperCase()

  return (
    <Document
      title={`${invoice.invoiceNumber} Damage Invoice`}
      author={invoice.hotelName}
      subject="Room damage invoice"
    >
      <Page size="A4" style={styles.page}>
        <View style={styles.content}>
          <View style={styles.header}>
            <View style={styles.brandBlock}>
              <View style={styles.logoFrame}>
                {invoice.hotelLogo ? (
                  <Image src={invoice.hotelLogo} style={styles.logo} />
                ) : (
                  <View style={styles.logoFallback}>
                    <Text>{hotelInitials || 'H'}</Text>
                  </View>
                )}
              </View>
              <View>
                <Text style={styles.eyebrow}>Damage Invoice</Text>
                <Text style={styles.title}>Invoice</Text>
                <Text style={styles.subtitle}>{invoice.hotelName}</Text>
              </View>
            </View>

            <View style={styles.metaBox}>
              <View style={styles.metaRow}>
                <Text style={styles.metaLabel}>Invoice No.</Text>
                <Text style={styles.metaValue}>{invoice.invoiceNumber}</Text>
              </View>
              {invoice.reservationId && (
                <View style={styles.metaRow}>
                  <Text style={styles.metaLabel}>Reservation</Text>
                  <Text style={styles.metaValue}>{invoice.reservationId}</Text>
                </View>
              )}
              <View style={styles.metaRow}>
                <Text style={styles.metaLabel}>Room</Text>
                <Text style={styles.metaValue}>{invoice.roomNumber}</Text>
              </View>
              <View style={styles.metaRow}>
                <Text style={styles.metaLabel}>Issued</Text>
                <Text style={styles.metaValue}>{formatDate(invoice.invoiceDate)}</Text>
              </View>
              <View style={styles.metaRow}>
                <Text style={styles.metaLabel}>Status</Text>
                <Text style={styles.metaValue}>{invoice.invoiceStatus.toUpperCase()}</Text>
              </View>
            </View>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Customer</Text>
            <View style={styles.grid}>
              <View style={styles.item}>
                <Text style={styles.label}>Name</Text>
                <Text style={styles.value}>{invoice.customerName}</Text>
              </View>
              {invoice.customerEmail && (
                <View style={styles.item}>
                  <Text style={styles.label}>Email</Text>
                  <Text style={styles.value}>{invoice.customerEmail}</Text>
                </View>
              )}
            </View>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Damage Details</Text>
            <View style={styles.damageBox}>
              <Text style={styles.damageLabel}>Description</Text>
              <Text style={styles.damageDescription}>{invoice.damageDescription}</Text>
            </View>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Amount Due</Text>
            <View style={styles.totals}>
              <View style={[styles.totalRow, styles.grandTotal]}>
                <Text style={styles.grandTotalLabel}>Total Damage Charge</Text>
                <Text style={styles.grandTotalValue}>
                  {formatCurrency(invoice.damageAmount, invoice.currency)}
                </Text>
              </View>
            </View>
          </View>
        </View>

        <View style={styles.footer}>
          <Text>{invoice.hotelName} — Damage Invoice</Text>
          <Text>Generated by Hotel Agency</Text>
        </View>
      </Page>
    </Document>
  )
}
