import { USER_ROLES, type UserRole } from "@/lib/abilities";

export const ASSIGNABLE_ROLES_BY_USER_ROLE: Partial<Record<UserRole, string[]>> = {
  [USER_ROLES.SUPER_ADMIN]: [],
  [USER_ROLES.AGENCY_OWNER]: [
    USER_ROLES.AGENCY_OWNER,
    USER_ROLES.PROPERTY_MANAGER,
    USER_ROLES.HOUSEKEEPING_MANAGER,
    USER_ROLES.FRONT_DESK_STAFF,
  ],
  [USER_ROLES.PROPERTY_MANAGER]: [
    USER_ROLES.PROPERTY_MANAGER,
    USER_ROLES.FRONT_DESK_STAFF,
    USER_ROLES.HOUSEKEEPING_MANAGER,
  ],
  [USER_ROLES.FRONT_DESK_STAFF]: [
    USER_ROLES.FRONT_DESK_STAFF,
    USER_ROLES.HOUSEKEEPING_MANAGER,
  ],
  [USER_ROLES.HOUSEKEEPING_MANAGER]: [
    USER_ROLES.HOUSEKEEPING_MANAGER,
    USER_ROLES.HOUSEKEEPING_EMPLOYEE,
  ],
};
