import { HOUSEKEEPING_TICKET_STATUS, HOUSEKEEPING_TICKET_PRIORITY, HOUSEKEEPING_TICKET_TYPE } from "./ticket";

export const STATUS_COLOR_KEY = {
  [HOUSEKEEPING_TICKET_STATUS.TO_DO]: "secondary",
  [HOUSEKEEPING_TICKET_STATUS.IN_PROGRESS]: "info",
  [HOUSEKEEPING_TICKET_STATUS.REVIEW]: "warning",
  [HOUSEKEEPING_TICKET_STATUS.DONE]: "success",
} as const;

export const PRIORITY_COLOR_KEY = {
  [HOUSEKEEPING_TICKET_PRIORITY.LOW]: "success",
  [HOUSEKEEPING_TICKET_PRIORITY.MEDIUM]: "warning",
  [HOUSEKEEPING_TICKET_PRIORITY.HIGH]: "error",
} as const;

export const TICKET_TYPE_COLOR_KEY = {
  [HOUSEKEEPING_TICKET_TYPE.TASK]: "info",
  [HOUSEKEEPING_TICKET_TYPE.ISSUE]: "error",
  [HOUSEKEEPING_TICKET_TYPE.INSPECTION]: "warning",
  [HOUSEKEEPING_TICKET_TYPE.MAINTENANCE_REQUEST]: "success",
} as const;
